### ISSUE TITLE
Roadmap (ADR)

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-gazebo-grasping-sandbox#2]
This sort of roadmap serves also as an [`Architectural Decision Record (ADR)`](https://en.wikipedia.org/wiki/Architectural_decision). 

### Foreword
- `ARE` makes the architecture unnecessarily heavier. Plus, it doesn't seem we can exploit the springy model for contact detection as we don't have recall springs in the distal phalanxes and thus LSSVM doesn't learn anything meaningful. 
- `cardinal-points-grasp` expects the availability of a bunch of components (`IOL`, `SFM`, `ARE`...) that are very difficult to replicate in the sandbox right now.

### Plan
- [x] Simply rely on the Cartesian and Gaze I/F's for performing movements in the operational space.
- [x] Get the point cloud from the simulated depth sensor.
- [x] Segment out points on the table with a naive approach (e.g. RANSAC).
- [x] Use `find-superquadric` to get the best SQ representing the segmented bottle point set.
- [x] Close the fingers around the object using a target configuration in position hoping this will suffice. A well-tweaked configuration should do the job, plus the low-level torque control in Gazebo should help out.
- [x] Start off with a preprogrammed grasp to see if the object can be lifted up at least.
- [x] Visualize by means of VTK what's going on under the hood: segmentation of table, SQ fitting object, grasp candidates.
- [x] We may build on the original idea of Cardinal Points Grasp:
    - [x] Implement side grasps.
    - [x] Implement top grasps.

### Addendum
- [x] Move the repo to https://github.com/robotology and update the Gitpod badge plus all links in the documentation.
- [x] Craft release `v1.0.0` (thus, enable <kbd>Releases</kbd> view in the homepage).
- [x] Make an announcement on https://spectrum.chat/icub as well as spread the news internally by updating the management issues.
- [x] Churn out `v1.1.0` sporting:
    - the script to clean up hanging resources.
    - the desktop GUI is rescaled to fit the browser window.
    - an easy way to transfer files/dirs using `magic-wormhole`.
    - fix of #24.

**Comment by pattacini** [comment]
PR #5 already allowed to get some of the above points done ✔

**Comment by pattacini** [comment]
PR #7 completes some of the outstanding points of the DoE ✔.
In particular, it addresses point cloud segmentation and fitting.

**Comment by pattacini** [comment]
PR #9 allows for visualizing the acquired information in the 3D space.

**Comment by pattacini** [comment]
PR #10 implements side grasps ✔

**Comment by pattacini** [comment]
PR #16 allows randomizing the object locations ✔

**Comment by pattacini** [comment]
PR #17 adds up a further object smaller than the bottle in order to showcase top grasps.

**Comment by pattacini** [comment]
PR #18 allows for encoding top grasps ✔️

**Comment by pattacini** [comment]
PR #20 allows for managing multiple objects on the table ✔️

**Comment by pattacini** [comment]
PR #22 provides the website ✔️

**Comment by pattacini** [comment]
Announcement made on Spectrum: see https://spectrum.chat/icub/research-news/icub-is-manipulation-ready-in-gazebo~5c7f34df-2f50-4b31-8526-e8bf7a35ec7b ✔

**Comment by pattacini** [comment]
[Release v1.1.0](https://github.com/robotology/icub-gazebo-grasping-sandbox/releases/tag/v1.1.0) published ✔

This roadmap can be considered fully accomplished! ✨
